FROM ghcr.io/forkbombeu/didroom_microservices:stable

ENV ZENCODE_DIR=/app/credential_issuer
ENV PUBLIC_DIR=/app/public/credential_issuer
ENV BASEPATH=/credential_issuer
ENV MS_URL=https://dev.issuer1.forkbomb.eu/credential_issuer
ENV MS_NAME=ci_forkbomb_test_issuer

COPY credential_issuer /app/credential_issuer
COPY public/credential_issuer /app/public/credential_issuer
