FROM ghcr.io/forkbombeu/didroom_microservices:stable

ENV ZENCODE_DIR=/app/relying_party
ENV PUBLIC_DIR=/app/public/relying_party
ENV BASEPATH=/relying_party
ENV MS_URL=https://dev.relying-party1.forkbomb.eu/relying_party
ENV MS_NAME=rp_dev_relying_party

COPY relying_party /app/relying_party
COPY public/relying_party /app/public/relying_party
